version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_finance_tracker
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    container_name: backend_finance_tracker
    restart: always
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:1234@postgres_finance_tracker:5432/finance_db
  frontend:
    image: nginx:latest
    container_name: frontend_finance_tracker
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  nginx:
    image: nginx:latest
    container_name: nginx_finance_tracker
    restart: always
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

volumes:
  postgres_data:

