version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_finance_tracker
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: finance_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
    container_name: backend_finance_tracker
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:1234@postgres_finance_tracker:5432/finance_db

volumes:
  postgres_data:
